### ISSUE TITLE
Registry Operator unsuccessfully launching the registry viewer

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1014]
## Which area this feature is related to?

/kind bug

### Which area this bug is related to?

/area registry

### Go project

**Operating System and version:** N/A

**Go Pkg Version:** 1.13

## Bug Summary

**Describe the bug:**

The registry viewer fails to parse a JSON config for the deployment environment which results in the registry viewer boot looping.

**To Reproduce:** 

After setting up the operator, use the following to deploy with headless mode disabled:

```bash
cat <<EOF | oc apply -f -
apiVersion: registry.devfile.io/v1alpha1
kind: DevfileRegistry
metadata:
  name: devfile-registry
spec:
  devfileIndexImage: quay.io/devfile/devfile-index:next
EOF
```

## Expected behavior

Registry viewer should deploy successful with the following output:

```
react-env: Writing runtime env /app/apps/registry-viewer/public/__ENV.js
info  - Loaded env from /app/apps/registry-viewer/.env.local
Listening on port 3000 url: http://localhost:3000
```

## Any logs, error output, screenshots etc? Provide the devfile that sees this bug, if applicable

```
react-env: Writing runtime env /app/apps/registry-viewer/public/__ENV.js
info  - Loaded env from /app/apps/registry-viewer/.env.local
Listening on port 3000 url: http://localhost:3000
SyntaxError: SyntaxError: Unexpected token \ in JSON at position 2, DEVFILE_REGISTRIES is an invalid json string
    at getDevfileRegistries (/app/apps/registry-viewer/dist/.next/server/chunks/222.js:64:15)
    at getServerSideProps (/app/apps/registry-viewer/dist/.next/server/pages/index.js:202:101)
    at Object.renderToHTML (/app/node_modules/next/dist/server/render.js:507:26)
    at async doRender (/app/node_modules/next/dist/server/base-server.js:720:34)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/app/node_modules/next/dist/server/base-server.js:828:28)
    at async /app/node_modules/next/dist/server/response-cache/index.js:83:36
```

### Any workaround?

None to run with the registry viewer currently, only headless mode will work.

### Suggestion on how to fix the bug

`Unexpected token \ in JSON at position 2` suggests that the escape characters used on [pkg/registry/configmap.go#L55](https://github.com/devfile/registry-operator/blob/71b9284a12630989184a8cf926a97543ef8da65f/pkg/registry/configmap.go#L55) are not escaping the inner quotes and are instead inserting the backslash characters into the JSON object value itself. Removing these might solve this issue.

**Target Date: 02-09-2023**

**Comment by michael-valdron** [comment]
blocked by #1016, #1019
