### ISSUE TITLE
Create new alpha version for devfile spec

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1382]
## Which area/kind this issue is related to?

/kind task

/area api

## Issue Description

The newest alpha version for the devfile spec `2.2.3-alpha` has not been created yet. We need to create the new alpha version to update our latest schema to the next release.

The job `publish-json-schema` is failing due to the latest version of the spec being the latest stable version rather than the expected alpha version:

```
Traceback (most recent call last):
  File "/home/runner/work/api/api/devfile-web-repo/./python/src/api_workflow/api_workflow.py", line 322, in <module>
    main()
  File "/home/runner/work/api/api/devfile-web-repo/./python/src/api_workflow/api_workflow.py", line 294, in main
    stable_version = get_stable_version(inputted_version, release, path=config.stable_version)
  File "/home/runner/work/api/api/devfile-web-repo/./python/src/api_workflow/api_workflow.py", line 131, in get_stable_version
    assert compare_versions((inputted_version, "Inputted version"), (stable_version, "Stable version")) > 0, (
AssertionError: Version 2.2.2 is a stable version and cannot be updated unless theargument "--release" is passed
```

## Acceptance Criteria

- [ ] Update `+devfile:jsonschema:version=` on [pkg/apis/workspaces/v1alpha2/doc.go#L21](https://github.com/devfile/api/blob/97165a52254f96c64d42b069d8b3eb83bb9a8972/pkg/apis/workspaces/v1alpha2/doc.go#L21) to current alpha version `2.2.3-alpha`
- [ ] Run `bash ./docker-run.sh ./build.sh` and commit changes

**Comment by michael-valdron** [comment]
Should be done to identify upcoming version changes.
