### ISSUE TITLE
Registry CI: Most nodejs stacks are incompatible with NodeJS 17 and are failing to build

### ISSUE THREAD

**Issue by johnmcollier** [devfile/api#665]
/kind bug

### Which area this bug is related to?

/area ci
/area registry

## Bug Summary
**Describe the bug:**
The [devfile/registry](https://github.com/devfile/registry) CI has started showing errors for the following nodejs stacks:

```
 FAILURE: FAILED TESTS:  nodejs-angular nodejs-nextjs nodejs-nuxtjs nodejs-react nodejs-vue 
 ```

`nodejs-nextjs`, `nodejs-nuxtjs`, `nodejs-react`, and `nodejs-vue` all have the same error, basically
```
 Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/project/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/project/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/project/node_modules/webpack/lib/NormalModule.js:471:10)
    at /project/node_modules/webpack/lib/NormalModule.js:503:5
    at /project/node_modules/webpack/lib/NormalModule.js:358:12
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/project/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/project/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/project/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /project/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /project/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
} 
```
Which seems to be related to webpack/webpack#14532.

`nodejs-angular` has a separate issue than the others:
```
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/releases/.
time="2021-11-01T20:19:44Z" level=debug msg="wait program exit" program=devrun 
time="2021-11-01T20:19:45Z" level=debug msg="no auth required" 
- Generating browser application bundles (phase: setup)...
An unhandled exception occurred: EBUSY: resource busy or locked, rmdir '/project/dist/nodejs-angular'
See "/tmp/ng-d6h7SQ/angular-errors.log" for further details.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I'm not sure what's the cause of the nodejs-angular failure, but moving the stack down to an older, NodeJS 16 image (node:16-slim specifically) did fix things.

**To Reproduce:**
See https://github.com/devfile/registry/runs/4070795791?check_suite_focus=true

Or https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/devfile_registry/79/pull-ci-devfile-registry-main-v4.7-registry-test/1455085083315671040

Or do:
1. `odo create nodejs-nextjs --starter nodejs-nextjs-starter`
2. `odo url create`
3. `odo push`

## Expected behavior
The tests do not fail.

**Comment by johnmcollier** [comment]
I think there's two separate issues at hand here:

1. Some issue with the `nginxinc/nginx-unprivileged:alpine` container used in nodejs-angular, nodejs-react, and nodejs-vue. 
   - What's weird is that the image hasn't been updated in 24 days, so I don't think it's an issue with the image itself
   
2. Some other issue affecting nextjs & nuxtjs stacks
